//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 06:18:39 ���� CST 
//


package com.chinasofti.login.service.ResourceXMLAnalyse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApplicationConfig element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="ApplicationConfig">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}AppConfig"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appConfig"
})
@XmlRootElement(name = "ApplicationConfig")
public class ApplicationConfig {

    @XmlElement(name = "AppConfig", required = true)
    protected AppConfig appConfig;

    /**
     * Gets the value of the appConfig property.
     * 
     * @return
     *     possible object is
     *     {@link AppConfig }
     *     
     */
    public AppConfig getAppConfig() {
        return appConfig;
    }

    /**
     * Sets the value of the appConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppConfig }
     *     
     */
    public void setAppConfig(AppConfig value) {
        this.appConfig = value;
    }

}
