//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 06:18:39 ���� CST 
//


package com.chinasofti.login.service.ResourceXMLAnalyse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModuleConfig element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="ModuleConfig">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}MUUID"/>
 *           &lt;element ref="{}ModuleCnname"/>
 *           &lt;element ref="{}ModuleEnname"/>
 *           &lt;element ref="{}ModuleNavUrl"/>
 *           &lt;element ref="{}MSerialIndex"/>
 *           &lt;element ref="{}MLeftFrameEnabled"/>
 *           &lt;element ref="{}MEnabled"/>
 *           &lt;element ref="{}NeedRight"/>
 *           &lt;element ref="{}MAdminFlag"/>
 *           &lt;element ref="{}ModuleDesc"/>
 *           &lt;element ref="{}LeftFirst"/>
 *           &lt;element ref="{}MCreateTime"/>
 *           &lt;element ref="{}MDeveloper"/>
 *           &lt;element ref="{}ModuleCode"/>
 *           &lt;element ref="{}MProtoType"/>
 *           &lt;element ref="{}MHelpURL"/>
 *           &lt;element ref="{}ResourceReg" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "muuid",
    "moduleCnname",
    "moduleEnname",
    "moduleNavUrl",
    "mSerialIndex",
    "mLeftFrameEnabled",
    "mEnabled",
    "needRight",
    "mAdminFlag",
    "moduleDesc",
    "leftFirst",
    "mCreateTime",
    "mDeveloper",
    "moduleCode",
    "mProtoType",
    "mHelpURL",
    "resourceReg"
})
@XmlRootElement(name = "ModuleConfig")
public class ModuleConfig {

    @XmlElement(name = "MUUID", required = true)
    protected String muuid;
    @XmlElement(name = "ModuleCnname", required = true)
    protected String moduleCnname;
    @XmlElement(name = "ModuleEnname", required = true)
    protected String moduleEnname;
    @XmlElement(name = "ModuleNavUrl", required = true)
    protected String moduleNavUrl;
    @XmlElement(name = "MSerialIndex", required = true)
    protected String mSerialIndex;
    @XmlElement(name = "MLeftFrameEnabled")
    protected byte mLeftFrameEnabled;
    @XmlElement(name = "MEnabled", required = true)
    protected String mEnabled;
    @XmlElement(name = "NeedRight", required = true)
    protected String needRight;
    @XmlElement(name = "MAdminFlag", required = true)
    protected String mAdminFlag;
    @XmlElement(name = "ModuleDesc", required = true)
    protected String moduleDesc;
    @XmlElement(name = "LeftFirst", required = true)
    protected String leftFirst;
    @XmlElement(name = "MCreateTime", required = true)
    protected String mCreateTime;
    @XmlElement(name = "MDeveloper", required = true)
    protected String mDeveloper;
    @XmlElement(name = "ModuleCode", required = true)
    protected String moduleCode;
    @XmlElement(name = "MProtoType", required = true)
    protected String mProtoType;
    @XmlElement(name = "MHelpURL", required = true)
    protected String mHelpURL;
    @XmlElement(name = "ResourceReg", required = true)
    protected List<ResourceReg> resourceReg;

    /**
     * Gets the value of the muuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUUID() {
        return muuid;
    }

    /**
     * Sets the value of the muuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUUID(String value) {
        this.muuid = value;
    }

    /**
     * Gets the value of the moduleCnname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleCnname() {
        return moduleCnname;
    }

    /**
     * Sets the value of the moduleCnname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleCnname(String value) {
        this.moduleCnname = value;
    }

    /**
     * Gets the value of the moduleEnname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleEnname() {
        return moduleEnname;
    }

    /**
     * Sets the value of the moduleEnname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleEnname(String value) {
        this.moduleEnname = value;
    }

    /**
     * Gets the value of the moduleNavUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleNavUrl() {
        return moduleNavUrl;
    }

    /**
     * Sets the value of the moduleNavUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleNavUrl(String value) {
        this.moduleNavUrl = value;
    }

    /**
     * Gets the value of the mSerialIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSerialIndex() {
        return mSerialIndex;
    }

    /**
     * Sets the value of the mSerialIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSerialIndex(String value) {
        this.mSerialIndex = value;
    }

    /**
     * Gets the value of the mLeftFrameEnabled property.
     * 
     */
    public byte getMLeftFrameEnabled() {
        return mLeftFrameEnabled;
    }

    /**
     * Sets the value of the mLeftFrameEnabled property.
     * 
     */
    public void setMLeftFrameEnabled(byte value) {
        this.mLeftFrameEnabled = value;
    }

    /**
     * Gets the value of the mEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEnabled() {
        return mEnabled;
    }

    /**
     * Sets the value of the mEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEnabled(String value) {
        this.mEnabled = value;
    }

    /**
     * Gets the value of the needRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeedRight() {
        return needRight;
    }

    /**
     * Sets the value of the needRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeedRight(String value) {
        this.needRight = value;
    }

    /**
     * Gets the value of the mAdminFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAdminFlag() {
        return mAdminFlag;
    }

    /**
     * Sets the value of the mAdminFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAdminFlag(String value) {
        this.mAdminFlag = value;
    }

    /**
     * Gets the value of the moduleDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * Sets the value of the moduleDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleDesc(String value) {
        this.moduleDesc = value;
    }

    /**
     * Gets the value of the leftFirst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftFirst() {
        return leftFirst;
    }

    /**
     * Sets the value of the leftFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftFirst(String value) {
        this.leftFirst = value;
    }

    /**
     * Gets the value of the mCreateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCreateTime() {
        return mCreateTime;
    }

    /**
     * Sets the value of the mCreateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCreateTime(String value) {
        this.mCreateTime = value;
    }

    /**
     * Gets the value of the mDeveloper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMDeveloper() {
        return mDeveloper;
    }

    /**
     * Sets the value of the mDeveloper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMDeveloper(String value) {
        this.mDeveloper = value;
    }

    /**
     * Gets the value of the moduleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * Sets the value of the moduleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleCode(String value) {
        this.moduleCode = value;
    }

    /**
     * Gets the value of the mProtoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMProtoType() {
        return mProtoType;
    }

    /**
     * Sets the value of the mProtoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMProtoType(String value) {
        this.mProtoType = value;
    }

    /**
     * Gets the value of the mHelpURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMHelpURL() {
        return mHelpURL;
    }

    /**
     * Sets the value of the mHelpURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMHelpURL(String value) {
        this.mHelpURL = value;
    }

    /**
     * Gets the value of the resourceReg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceReg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceReg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceReg }
     * 
     * 
     */
    public List<ResourceReg> getResourceReg() {
        if (resourceReg == null) {
            resourceReg = new ArrayList<ResourceReg>();
        }
        return this.resourceReg;
    }

}
