//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 06:18:39 ���� CST 
//


package com.chinasofti.login.service.ResourceXMLAnalyse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ta.cchs.jaxb.sample.bean.net package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MSerialIndex_QNAME = new QName("", "MSerialIndex");
    private final static QName _MLeftFrameEnabled_QNAME = new QName("", "MLeftFrameEnabled");
    private final static QName _ResUrl_QNAME = new QName("", "ResUrl");
    private final static QName _ModuleNavUrl_QNAME = new QName("", "ModuleNavUrl");
    private final static QName _FentryFlag_QNAME = new QName("", "FentryFlag");
    private final static QName _MUUID_QNAME = new QName("", "MUUID");
    private final static QName _MDeveloper_QNAME = new QName("", "MDeveloper");
    private final static QName _MEnabled_QNAME = new QName("", "MEnabled");
    private final static QName _ResUUID_QNAME = new QName("", "ResUUID");
    private final static QName _ModuleEnname_QNAME = new QName("", "ModuleEnname");
    private final static QName _ModuleCnname_QNAME = new QName("", "ModuleCnname");
    private final static QName _ResCode_QNAME = new QName("", "ResCode");
    private final static QName _ResDesc_QNAME = new QName("", "ResDesc");
    private final static QName _MProtoType_QNAME = new QName("", "MProtoType");
    private final static QName _ResSerialIndex_QNAME = new QName("", "ResSerialIndex");
    private final static QName _MAdminFlag_QNAME = new QName("", "MAdminFlag");
    private final static QName _NeedRight_QNAME = new QName("", "NeedRight");
    private final static QName _ResParentUUID_QNAME = new QName("", "ResParentUUID");
    private final static QName _ModuleDesc_QNAME = new QName("", "ModuleDesc");
    private final static QName _LeftFirst_QNAME = new QName("", "LeftFirst");
    private final static QName _ResCnname_QNAME = new QName("", "ResCnname");
    private final static QName _ResVersion_QNAME = new QName("", "ResVersion");
    private final static QName _MCreateTime_QNAME = new QName("", "MCreateTime");
    private final static QName _ModuleCode_QNAME = new QName("", "ModuleCode");
    private final static QName _Status_QNAME = new QName("", "Status");
    private final static QName _ClassCode_QNAME = new QName("", "ClassCode");
    private final static QName _MHelpURL_QNAME = new QName("", "MHelpURL");
    private final static QName _ResLevelCode_QNAME = new QName("", "ResLevelCode");
    private final static QName _ResCreateTime_QNAME = new QName("", "ResCreateTime");
    private final static QName _EntryFlag_QNAME = new QName("", "EntryFlag");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ta.cchs.jaxb.sample.bean.net
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModuleConfig }
     * 
     */
    public ModuleConfig createModuleConfig() {
        return new ModuleConfig();
    }

    /**
     * Create an instance of {@link ApplicationConfig }
     * 
     */
    public ApplicationConfig createApplicationConfig() {
        return new ApplicationConfig();
    }

    /**
     * Create an instance of {@link AppConfig }
     * 
     */
    public AppConfig createAppConfig() {
        return new AppConfig();
    }

    /**
     * Create an instance of {@link ResourceReg }
     * 
     */
    public ResourceReg createResourceReg() {
        return new ResourceReg();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MSerialIndex")
    public JAXBElement<String> createMSerialIndex(String value) {
        return new JAXBElement<String>(_MSerialIndex_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MLeftFrameEnabled")
    public JAXBElement<Byte> createMLeftFrameEnabled(Byte value) {
        return new JAXBElement<Byte>(_MLeftFrameEnabled_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResUrl")
    public JAXBElement<String> createResUrl(String value) {
        return new JAXBElement<String>(_ResUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModuleNavUrl")
    public JAXBElement<String> createModuleNavUrl(String value) {
        return new JAXBElement<String>(_ModuleNavUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FentryFlag")
    public JAXBElement<String> createFentryFlag(String value) {
        return new JAXBElement<String>(_FentryFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MUUID")
    public JAXBElement<String> createMUUID(String value) {
        return new JAXBElement<String>(_MUUID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MDeveloper")
    public JAXBElement<String> createMDeveloper(String value) {
        return new JAXBElement<String>(_MDeveloper_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MEnabled")
    public JAXBElement<String> createMEnabled(String value) {
        return new JAXBElement<String>(_MEnabled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResUUID")
    public JAXBElement<String> createResUUID(String value) {
        return new JAXBElement<String>(_ResUUID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModuleEnname")
    public JAXBElement<String> createModuleEnname(String value) {
        return new JAXBElement<String>(_ModuleEnname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModuleCnname")
    public JAXBElement<String> createModuleCnname(String value) {
        return new JAXBElement<String>(_ModuleCnname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResCode")
    public JAXBElement<String> createResCode(String value) {
        return new JAXBElement<String>(_ResCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResDesc")
    public JAXBElement<String> createResDesc(String value) {
        return new JAXBElement<String>(_ResDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MProtoType")
    public JAXBElement<String> createMProtoType(String value) {
        return new JAXBElement<String>(_MProtoType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResSerialIndex")
    public JAXBElement<String> createResSerialIndex(String value) {
        return new JAXBElement<String>(_ResSerialIndex_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MAdminFlag")
    public JAXBElement<String> createMAdminFlag(String value) {
        return new JAXBElement<String>(_MAdminFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NeedRight")
    public JAXBElement<String> createNeedRight(String value) {
        return new JAXBElement<String>(_NeedRight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResParentUUID")
    public JAXBElement<String> createResParentUUID(String value) {
        return new JAXBElement<String>(_ResParentUUID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModuleDesc")
    public JAXBElement<String> createModuleDesc(String value) {
        return new JAXBElement<String>(_ModuleDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeftFirst")
    public JAXBElement<String> createLeftFirst(String value) {
        return new JAXBElement<String>(_LeftFirst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResCnname")
    public JAXBElement<String> createResCnname(String value) {
        return new JAXBElement<String>(_ResCnname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResVersion")
    public JAXBElement<String> createResVersion(String value) {
        return new JAXBElement<String>(_ResVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MCreateTime")
    public JAXBElement<String> createMCreateTime(String value) {
        return new JAXBElement<String>(_MCreateTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModuleCode")
    public JAXBElement<String> createModuleCode(String value) {
        return new JAXBElement<String>(_ModuleCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ClassCode")
    public JAXBElement<String> createClassCode(String value) {
        return new JAXBElement<String>(_ClassCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MHelpURL")
    public JAXBElement<String> createMHelpURL(String value) {
        return new JAXBElement<String>(_MHelpURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResLevelCode")
    public JAXBElement<String> createResLevelCode(String value) {
        return new JAXBElement<String>(_ResLevelCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResCreateTime")
    public JAXBElement<String> createResCreateTime(String value) {
        return new JAXBElement<String>(_ResCreateTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EntryFlag")
    public JAXBElement<String> createEntryFlag(String value) {
        return new JAXBElement<String>(_EntryFlag_QNAME, String.class, null, value);
    }

}
