//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 06:18:39 ���� CST 
//


package com.chinasofti.login.service.ResourceXMLAnalyse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceReg element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="ResourceReg">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}ResUUID"/>
 *           &lt;element ref="{}ResCode"/>
 *           &lt;element ref="{}ResCnname"/>
 *           &lt;element ref="{}ResCreateTime"/>
 *           &lt;element ref="{}ResUrl"/>
 *           &lt;element ref="{}ResParentUUID"/>
 *           &lt;element ref="{}ResVersion"/>
 *           &lt;element ref="{}Status"/>
 *           &lt;element ref="{}ResLevelCode"/>
 *           &lt;element ref="{}EntryFlag"/>
 *           &lt;element ref="{}FentryFlag"/>
 *           &lt;element ref="{}ResDesc"/>
 *           &lt;element ref="{}ResSerialIndex"/>
 *           &lt;element ref="{}ClassCode"/>
 *           &lt;element ref="{}NeedRight"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resUUID",
    "resCode",
    "resCnname",
    "resCreateTime",
    "resUrl",
    "resParentUUID",
    "resVersion",
    "status",
    "resLevelCode",
    "entryFlag",
    "fentryFlag",
    "resDesc",
    "resSerialIndex",
    "classCode",
    "needRight"
})
@XmlRootElement(name = "ResourceReg")
public class ResourceReg {

    @XmlElement(name = "ResUUID", required = true)
    protected String resUUID;
    @XmlElement(name = "ResCode", required = true)
    protected String resCode;
    @XmlElement(name = "ResCnname", required = true)
    protected String resCnname;
    @XmlElement(name = "ResCreateTime", required = true)
    protected String resCreateTime;
    @XmlElement(name = "ResUrl", required = true)
    protected String resUrl;
    @XmlElement(name = "ResParentUUID", required = true)
    protected String resParentUUID;
    @XmlElement(name = "ResVersion", required = true)
    protected String resVersion;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "ResLevelCode", required = true)
    protected String resLevelCode;
    @XmlElement(name = "EntryFlag", required = true)
    protected String entryFlag;
    @XmlElement(name = "FentryFlag", required = true)
    protected String fentryFlag;
    @XmlElement(name = "ResDesc", required = true)
    protected String resDesc;
    @XmlElement(name = "ResSerialIndex", required = true)
    protected String resSerialIndex;
    @XmlElement(name = "ClassCode", required = true)
    protected String classCode;
    @XmlElement(name = "NeedRight", required = true)
    protected String needRight;

    /**
     * Gets the value of the resUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResUUID() {
        return resUUID;
    }

    /**
     * Sets the value of the resUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResUUID(String value) {
        this.resUUID = value;
    }

    /**
     * Gets the value of the resCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResCode() {
        return resCode;
    }

    /**
     * Sets the value of the resCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResCode(String value) {
        this.resCode = value;
    }

    /**
     * Gets the value of the resCnname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResCnname() {
        return resCnname;
    }

    /**
     * Sets the value of the resCnname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResCnname(String value) {
        this.resCnname = value;
    }

    /**
     * Gets the value of the resCreateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResCreateTime() {
        return resCreateTime;
    }

    /**
     * Sets the value of the resCreateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResCreateTime(String value) {
        this.resCreateTime = value;
    }

    /**
     * Gets the value of the resUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * Sets the value of the resUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResUrl(String value) {
        this.resUrl = value;
    }

    /**
     * Gets the value of the resParentUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResParentUUID() {
        return resParentUUID;
    }

    /**
     * Sets the value of the resParentUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResParentUUID(String value) {
        this.resParentUUID = value;
    }

    /**
     * Gets the value of the resVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResVersion() {
        return resVersion;
    }

    /**
     * Sets the value of the resVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResVersion(String value) {
        this.resVersion = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the resLevelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResLevelCode() {
        return resLevelCode;
    }

    /**
     * Sets the value of the resLevelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResLevelCode(String value) {
        this.resLevelCode = value;
    }

    /**
     * Gets the value of the entryFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryFlag() {
        return entryFlag;
    }

    /**
     * Sets the value of the entryFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryFlag(String value) {
        this.entryFlag = value;
    }

    /**
     * Gets the value of the fentryFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFentryFlag() {
        return fentryFlag;
    }

    /**
     * Sets the value of the fentryFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFentryFlag(String value) {
        this.fentryFlag = value;
    }

    /**
     * Gets the value of the resDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResDesc() {
        return resDesc;
    }

    /**
     * Sets the value of the resDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResDesc(String value) {
        this.resDesc = value;
    }

    /**
     * Gets the value of the resSerialIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResSerialIndex() {
        return resSerialIndex;
    }

    /**
     * Sets the value of the resSerialIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResSerialIndex(String value) {
        this.resSerialIndex = value;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassCode(String value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the needRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeedRight() {
        return needRight;
    }

    /**
     * Sets the value of the needRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeedRight(String value) {
        this.needRight = value;
    }

}
